### ISSUE TITLE
FID for FFHQ 1024

### ISSUE THREAD

**Issue by betterze** [mit-han-lab/anycost-gan#1]
Dear mit-han-lab, 

Thank you for sharing with us this great work, I really like it.

In Table 1, you show that multiple resolution outputs have higher image quality compared to single resolution training in config E. Have you try config F, which is the standard stylegan2 mode? 

According to [FFHQ 1024 leadboard](https://paperswithcode.com/sota/image-generation-on-ffhq), the stylegan2 has FID of 2.84, while anycost GAN has FID of 2.99, which is a little bit worse. So I am wondering if you use config F as standard StyleGAN2, will you get better results than standard StyleGAN2? 

Thank you for your help.

Best Wishes,

Alex

**Comment by tonylins** [comment]
Hi Alex,

For Table 1, we used Config-E as shown in the caption, which is just for a faster ablation study. Under this setting, our FID is better than single-resolution StyleGAN2.

For Config-F, when just supporting multi-resolution, we are able to get FID 2.73 during half of the training, which is slightly better. But we did not train the generator to a full convergence since we still need to support adaptive-channel in the next phase. We expect you can get a better FID if you train the multi-resolution generator longer.

Best,
Ji

**Comment by betterze** [comment]
Thank you for your reply. I understand it now.

**Comment by duongquangvinh** [comment]
What is the meaning of multi- and single- resolution?

**Comment by tonylins** [comment]
> What is the meaning of multi- and single- resolution?

Single-resolution means that the generator is trained to generate images of only one resolution (e.g., 1024). Multi-resolution means that the generator can generate images of different resolutions (e.g., 128/256/512/1024).
